# aarch64-alpine-linux-musl
# x86_64-alpine-linux-musl
ARG ARCH=x86_64-alpine-linux-musl
ARG REMOTE_TAG=v2.0.6
ARG VARIANT=std

FROM alpine as builder

ARG ARCH
ARG REMOTE_TAG
ARG VARIANT

ENV container=docker TERM=xterm LC_ALL=en_US LANGUAGE=en_US LANG=en_US.UTF-8
#ENV DEBIAN_FRONTEND=noninteractive

# Install packages for build variant
RUN apk add --update \
        build-base \
        git \
        bash \
        linux-headers \
        argp-standalone && \
        rm -rf /var/cache/apk/*

# Work dir for GLS Basic Station
WORKDIR /app

# Checkout and compile remote code
COPY builder/* ./
RUN chmod +x *.sh
#COPY . basicstation/
RUN ARCH=${ARCH} REMOTE_TAG=${REMOTE_TAG} VARIANT=${VARIANT} ./build.sh
##RUN git clone https://github.com/LouneCode/gls-basicstation.git basicstation
##COPY setup.gmk basicstation/.
##COPY src/aio.c basicstation/src/.
#RUN cd basicstation && make super-clean && make platform=corecell variant=std
##RUN REMOTE_TAG=${REMOTE_TAG} VARIANT=${VARIANT} ./build.sh


FROM alpine as runner
ARG ARCH
ARG REMOTE_TAG
ARG VARIANT

# Image metadata
LABEL maintainer="Only husky in the village <postia.lounelle@live.com>"
LABEL authors="Only husky in the village"
LABEL org.label-schema.schema-version="1.0"
#LABEL org.label-schema.build-date=${BUILD_DATE}
LABEL org.label-schema.name="GLS LoRaWAN Basics™ Station "
LABEL org.label-schema.version="Version based on ${REMOTE_TAG}-${VARIANT}"
LABEL org.label-schema.description="GLS LoRaWAN Basics™ Station gateway with fine timestamp"
LABEL org.label-schema.vcs-type="Git"
LABEL org.label-schema.vcs-url="https://github.com/lorabasics/basicstation.git"
LABEL org.label-schema.vcs-ref=${TAG}
LABEL org.label-schema.arch=${ARCH}
LABEL org.label-schema.license="BSD License 2.0"

ENV container=docker TERM=xterm LC_ALL=en_US LANGUAGE=en_US LANG=en_US.UTF-8 TZ=Europe/Helsinki
#ENV DEBIAN_FRONTEND=noninteractive

# locale
# sudo commmand
# non-privileged user
# remove apt cache
RUN apk add --update --no-cache \
        musl musl-utils musl-locales tzdata sed \
        sudo bash gpiod && \
        echo "nonprivuser ALL=(ALL) NOPASSWD:ALL /bin/su" >> /etc/sudoers && \
        addgroup -S nonprivuser && adduser -S nonprivuser -G nonprivuser && \
        chown -R nonprivuser:nonprivuser /home/nonprivuser && \
        cp /usr/share/zoneinfo/Europe/London /etc/localtime && \
        echo 'export LC_ALL=en_US.UTF-8' >> /etc/profile.d/locale.sh && \
        sed -i 's|LANG=C.UTF-8|LANG=en_US.UTF-8|' /etc/profile.d/locale.sh  && \
        rm -rf /var/cache/apk/*

# Work dir for GLS Basic Station
WORKDIR /app

# Copy fles from builder and repo
COPY --from=builder /app/basicstation/build-corecell-${VARIANT}/bin/* ./design-corecell/bin/
COPY runner/* ./

# Set nonpriv user env
RUN chmod +x *.sh && \
    chown -R nonprivuser /app && \
    addgroup nonprivuser dialout

USER nonprivuser

# Launch our binary on container startup.
ENTRYPOINT ["/app/start.sh"]